.TH "CategoryStream.hh" 3 "3 Oct 2012" "Version 1.0" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CategoryStream.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <log4cpp/Portability.hh>\fP
.br
\fC#include <log4cpp/Priority.hh>\fP
.br
\fC#include <ios>\fP
.br
\fC#include <log4cpp/Manipulator.hh>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::CategoryStream\fP"
.br
.RI "\fIThis class enables streaming simple types and objects to a category. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "LOG4CPP_EXPORT \fBCategoryStream\fP & \fBlog4cpp::eol\fP (\fBCategoryStream\fP &os)"
.br
.RI "\fIeol manipulator \fP"
.ti -1c
.RI "LOG4CPP_EXPORT \fBCategoryStream\fP & \fBlog4cpp::left\fP (\fBCategoryStream\fP &os)"
.br
.RI "\fIleft manipulator \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "LOG4CPP_EXPORT \fBlog4cpp::Category\fP"
.br
.ti -1c
.RI "LOG4CPP_EXPORT \fBlog4cpp::CategoryStream\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
