.TH "DummyThreads.hh" 3 "3 Oct 2012" "Version 1.0" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DummyThreads.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <log4cpp/Portability.hh>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.ti -1c
.RI "namespace \fBlog4cpp::threading\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::threading::ThreadLocalDataHolder< T >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBlog4cpp::threading::Mutex\fP"
.br
.RI "\fIDummy type 'int' for \fBMutex\fP. \fP"
.ti -1c
.RI "typedef int \fBlog4cpp::threading::ScopedLock\fP"
.br
.RI "\fIDummy type 'int' defintion of \fBScopedLock\fP;. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static std::string \fBlog4cpp::threading::getThreadId\fP ()"
.br
.RI "\fIreturns the thread ID \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
