.TH "IdsaAppender.hh" 3 "3 Oct 2012" "Version 1.0" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IdsaAppender.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <log4cpp/Portability.hh>\fP
.br
\fC#include <string>\fP
.br
\fC#include <stdarg.h>\fP
.br
\fC#include <idsa.h>\fP
.br
\fC#include <log4cpp/AppenderSkeleton.hh>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::IdsaAppender\fP"
.br
.RI "\fI\fBIdsaAppender\fP is an \fBAppender\fP that sends LoggingEvents to the IDS/A logger and reference monitor by Marc Welz. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
