.TH "log4cpp::width" 3 "3 Oct 2012" "Version 1.0" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::width \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Manipulator.hh>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwidth\fP (unsigned int i)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "LOG4CPP_EXPORT std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBwidth\fP &w)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::width::width (unsigned int i)\fC [inline]\fP"
.PP
.SH "Friends And Related Function Documentation"
.PP 
.SS "LOG4CPP_EXPORT std::ostream& operator<< (std::ostream & os, const \fBwidth\fP & w)\fC [friend]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
