.TH "log4cpp::threading::ThreadLocalDataHolder" 3 "3 Oct 2012" "Version 1.0" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::threading::ThreadLocalDataHolder \- 
.SH SYNOPSIS
.br
.PP
\fC#include <BoostThreads.hh>\fP
.PP

.SS "template<typename T> class log4cpp::threading::ThreadLocalDataHolder< T >"


.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
