.TH "log4cpp::threading::ScopedLock" 3 "3 Oct 2012" "Version 1.0" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cpp::threading::ScopedLock \- definition of \fBScopedLock\fP;  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <PThreads.hh>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScopedLock\fP (\fBMutex\fP &mutex)"
.br
.ti -1c
.RI "\fB~ScopedLock\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
definition of \fBScopedLock\fP; 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cpp::threading::ScopedLock::ScopedLock (\fBMutex\fP & mutex)\fC [inline]\fP"
.PP
.SS "log4cpp::threading::ScopedLock::~ScopedLock ()\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
