.TH "OmniThreads.hh" 3 "3 Oct 2012" "Version 1.0" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OmniThreads.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <log4cpp/Portability.hh>\fP
.br
\fC#include <omnithread.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.ti -1c
.RI "namespace \fBlog4cpp::threading\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::threading::ThreadLocalDataHolder< T >\fP"
.br
.RI "\fIThis class holds Thread local data of type T, i.e. \fP"
.ti -1c
.RI "class \fBlog4cpp::threading::ThreadLocalDataHolder< T >::Holder\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef omni_mutex \fBlog4cpp::threading::Mutex\fP"
.br
.RI "\fIA simple, non recursive \fBMutex\fP. \fP"
.ti -1c
.RI "typedef omni_mutex_lock \fBlog4cpp::threading::ScopedLock\fP"
.br
.RI "\fIA simple 'resource acquisition is initialization' idiom type lock for \fBMutex\fP. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static std::string \fBlog4cpp::threading::getThreadId\fP ()"
.br
.RI "\fIreturns the thread ID \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
