.TH "Win32DebugAppender.hh" 3 "3 Oct 2012" "Version 1.0" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Win32DebugAppender.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'log4cpp/Export.hh'\fP
.br
\fC#include 'log4cpp/LayoutAppender.hh'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cpp\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cpp::Win32DebugAppender\fP"
.br
.RI "\fI\fBWin32DebugAppender\fP simply sends the log message to the default system debugger on Win32 systems. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cpp from the source code.
