/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CacheTubeService_CONSTANTS_H
#define CacheTubeService_CONSTANTS_H

#include "CacheTubeService_types.h"

namespace cachetube { namespace thrift {

class CacheTubeServiceConstants {
 public:
  CacheTubeServiceConstants();

};

extern const CacheTubeServiceConstants g_CacheTubeService_constants;

}} // namespace

#endif
