/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "CacheTubeService_constants.h"

namespace cachetube { namespace thrift {

const CacheTubeServiceConstants g_CacheTubeService_constants;

CacheTubeServiceConstants::CacheTubeServiceConstants() {
}

}} // namespace

